### ISSUE TITLE
Let's get to work!

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/Bayesian-Unobserved-Component-Models#1]
## todos

- [x] set up repo
- [x] upload the website
- [x] deploy the website
- [x] invite collaborators
- [x] create issues
- [x] assign issues
