### ISSUE TITLE
Let's get to work!

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/Bayesian-Unobserved-Component-Models#1]
## todos

- [ ] set up the repor and website
- [ ] the first version website version
- [ ] describe the LL model
- [ ] include sections
- [ ] assign sections and create issues
